image: "astral/uv:python3.13-trixie-slim"

variables:
  DEBIAN_FRONTEND: "noninteractive"
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: none

stages:
  - code-check
  - test
  - docs

############ Code Checks #############

.code-check-base:
  stage: code-check
  except:
    refs:
      - merge_requests
  before_script:
    - uv venv
    - uv sync --extra dev

mypy:
  extends: .code-check-base
  script:
    - uv run mypy ./src

ty:
  extends: .code-check-base
  script:
    - uv run ty check ./src

format:
  extends: .code-check-base
  script:
    - uv run ruff format --check ./src

lint:
  extends: .code-check-base
  script:
    - uv run ruff check ./src

################ Tests ################

.test-base:
  stage: test
  dependencies: []
  except:
    refs:
      - merge_requests
  before_get_sources:
    - apt -qqy update > /dev/null
    - apt -qqy --no-install-recommends install git make > /dev/null
  before_script:
    - uv venv
    - uv sync
    - git submodule update --init --depth 1 test_projects/${TEST_PROJECT} || true
  script:
    - uv run askiff -i test_projects/${TEST_PROJECT} --time-print
    - if [[ -n $(git diff --shortstat --submodule=diff) ]]; then git diff --submodule=diff --color=always; exit 1; fi

test-kicad9:
  extends: .test-base
  variables:
    TEST_PROJECT: "kicad9"

test-kicad10:
  extends: .test-base
  variables:
    TEST_PROJECT: "kicad10"

test-thor:
  extends: .test-base
  variables:
    TEST_PROJECT: "jetson-agx-thor-baseboard"

doc-test:
  stage: test
  dependencies: []
  except:
    refs:
      - merge_requests
  before_get_sources:
    - apt -qqy update > /dev/null
    - apt -qqy --no-install-recommends install git make graphviz> /dev/null
  before_script:
    - uv venv
    - uv sync --extra dev --extra docs
  script:
    - make -f Docs.Makefile doctest > docs.log
  artifacts:
    when: always
    paths:
      - docs.log

############ Documentation ############

build-docs:
  extends: doc-test
  stage: docs
  tags: ['docs']
  script:
    - make -f Docs.Makefile html > docs.log
    - tar cf $CI_DOCS_ARCHIVE -C .build/html/ .  
  artifacts:
    when: always
    paths:
      - docs.log
      - $CI_DOCS_ARCHIVE

